In [30]:
import numpy as np

In [31]:
a = np.array([[0,1,2], [3,4,5]])
b = np.array([[0,1,2,3], [4,5,6,7]])

In [32]:
c = np.dot(a.T, b)

In [33]:
print(c)

[[12 15 18 21]
 [16 21 26 31]
 [20 27 34 41]]


In [34]:
c.max()

41